sudo: required
services:
    - docker

before_install:
    - docker build -t matrixul/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true matrixul/docker-react npm run test -- --coverage
      
language: generic  